### PR TITLE
Export valid attachment position

### PR DESCRIPTION
**Pull request by slorber**
I'd like these to be exported so that lib clients can validate position on their side without duplicating this list.
In my case I built a wrapper for a tooltip component and I'd like my wrapper to also declare proptypes. 
Also need ability to validate positions at app startup time (ie I create HOC using positions) instead or runtime

Maybe my usecase is not that clear but I'm sure it's not a big deal to export these positions anyway

### CODE REVIEW

**Comment by souporserious** [comment]
How would someone consume this if it's being exported like that? Not sure I understand how it would work.

**Comment by slorber** [comment]
```javascript
export const OnbooardingHotspot = React.createClass({
  propTypes: {
    hotspotPosition: ReactTether.PositionPropType.isRequired,
  }
})
```

just if I build a wrapper around react-tether that expose a position prop i'd like to not declare list of position myself in my own code.

**Comment by souporserious** [comment]
Totally. I can't get it to work by calling `TetherComponent.attachmentPositions` though. Wondering if there is any way to do that? Maybe make it a getter or something. Seems kind of weird though.

**Comment by souporserious** [comment]
These should fall through your component and into the PropTypes of this one if the attachment position is not valid, right? If this is not the case, I'll reconsider exporting them.

**Pull request closed without merging**
