### PR TITLE
add license title, remove extra newline

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by waldyrious** [comment]
@souporserious not sure why you closed this with no feedback -- I'd appreciate hearing your thoughts. For future reference, the license was changed from ISC to MIT in c59da90.

**Comment by waldyrious** [comment]
Ah, I had forgotten about https://github.com/souporserious/react-motion-ui-pack/pull/53. I suppose the rationale was the same here.

**Comment by souporserious** [comment]
Sorry about that, yes same reasoning. I've always meant for all of my repos to be MIT.

**Comment by waldyrious** [comment]
Yeah, I figured it out. Is it because it's more popular? I always liked ISC for being even more compact and readable than MIT :)

**Comment by souporserious** [comment]
Honestly, I don't know 😞 haha. I just want everyone to be able to use the code I write with no worries.

**Comment by waldyrious** [comment]
Got it, thanks for clarifying 👍

**Pull request closed without merging**
